### chat api

GET http://localhost:6688/api/chat


### signup user
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "test",
    "email": "test@test.com",
    "password": "123456"
}


### signin user (vaild)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}
@token = {{signin.response.body.token}}

### get chat list
GET http://localhost:6688/api/chat
Authorization: Bearer {{token}}


### signin user (invaild)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "aaa@test.com",
    "password": "123456"
}
